
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("451a7a3a-0274-4a9b-8595-862d0f602595")>
#Region "Metadatos de relaciones en EDM"
<Assembly: EdmRelationshipAttribute("CSAdminBDModel", "Equipos_Contratos", "Equipos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Equipos), "Contratos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Contratos), True)>
<Assembly: EdmRelationshipAttribute("CSAdminBDModel", "Funciones_Contratos", "Funciones", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Funciones), "Contratos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Contratos), True)>
<Assembly: EdmRelationshipAttribute("CSAdminBDModel", "Personas_Contratos", "Personas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Personas), "Contratos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Contratos), True)>
<Assembly: EdmRelationshipAttribute("CSAdminBDModel", "SituacionesProfesionales_Contratos", "SituacionesProfesionales", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SituacionesProfesionales), "Contratos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Contratos), True)>
<Assembly: EdmRelationshipAttribute("CSAdminBDModel", "Personas_Equipos", "Personas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Personas), "Equipos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Equipos), True)>
<Assembly: EdmRelationshipAttribute("CSAdminBDModel", "Personas_Inasistencias", "Personas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Personas), "Inasistencias", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Inasistencias), True)>
<Assembly: EdmRelationshipAttribute("CSAdminBDModel", "Personas_PersonasTel", "Personas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Personas), "PersonasTel", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(PersonasTel), True)>
<Assembly: EdmRelationshipAttribute("CSAdminBDModel", "Personas_Usuarios", "Personas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Personas), "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Usuarios), True)>

#End Region

#Region "Contextos"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
Public Partial Class CSAdminBDEntities
    Inherits ObjectContext

    #Region "Constructores"

    ''' <summary>
    ''' Inicializa un nuevo objeto CSAdminBDEntities usando la cadena de conexión encontrada en la sección 'CSAdminBDEntities' del archivo de configuración de la aplicación.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=CSAdminBDEntities", "CSAdminBDEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto CSAdminBDEntities.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "CSAdminBDEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto CSAdminBDEntities.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "CSAdminBDEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Métodos parciales"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propiedades de ObjectSet"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Contratos() As ObjectSet(Of Contratos)
        Get
            If (_Contratos Is Nothing) Then
                _Contratos = MyBase.CreateObjectSet(Of Contratos)("Contratos")
            End If
            Return _Contratos
        End Get
    End Property

    Private _Contratos As ObjectSet(Of Contratos)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Equipos() As ObjectSet(Of Equipos)
        Get
            If (_Equipos Is Nothing) Then
                _Equipos = MyBase.CreateObjectSet(Of Equipos)("Equipos")
            End If
            Return _Equipos
        End Get
    End Property

    Private _Equipos As ObjectSet(Of Equipos)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Funciones() As ObjectSet(Of Funciones)
        Get
            If (_Funciones Is Nothing) Then
                _Funciones = MyBase.CreateObjectSet(Of Funciones)("Funciones")
            End If
            Return _Funciones
        End Get
    End Property

    Private _Funciones As ObjectSet(Of Funciones)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Inasistencias() As ObjectSet(Of Inasistencias)
        Get
            If (_Inasistencias Is Nothing) Then
                _Inasistencias = MyBase.CreateObjectSet(Of Inasistencias)("Inasistencias")
            End If
            Return _Inasistencias
        End Get
    End Property

    Private _Inasistencias As ObjectSet(Of Inasistencias)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Personas() As ObjectSet(Of Personas)
        Get
            If (_Personas Is Nothing) Then
                _Personas = MyBase.CreateObjectSet(Of Personas)("Personas")
            End If
            Return _Personas
        End Get
    End Property

    Private _Personas As ObjectSet(Of Personas)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property PersonasTel() As ObjectSet(Of PersonasTel)
        Get
            If (_PersonasTel Is Nothing) Then
                _PersonasTel = MyBase.CreateObjectSet(Of PersonasTel)("PersonasTel")
            End If
            Return _PersonasTel
        End Get
    End Property

    Private _PersonasTel As ObjectSet(Of PersonasTel)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property SituacionesProfesionales() As ObjectSet(Of SituacionesProfesionales)
        Get
            If (_SituacionesProfesionales Is Nothing) Then
                _SituacionesProfesionales = MyBase.CreateObjectSet(Of SituacionesProfesionales)("SituacionesProfesionales")
            End If
            Return _SituacionesProfesionales
        End Get
    End Property

    Private _SituacionesProfesionales As ObjectSet(Of SituacionesProfesionales)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Usuarios() As ObjectSet(Of Usuarios)
        Get
            If (_Usuarios Is Nothing) Then
                _Usuarios = MyBase.CreateObjectSet(Of Usuarios)("Usuarios")
            End If
            Return _Usuarios
        End Get
    End Property

    Private _Usuarios As ObjectSet(Of Usuarios)

    #End Region

    #Region "Métodos AddTo"

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Contratos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToContratos(ByVal contratos As Contratos)
        MyBase.AddObject("Contratos", contratos)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Equipos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToEquipos(ByVal equipos As Equipos)
        MyBase.AddObject("Equipos", equipos)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Funciones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToFunciones(ByVal funciones As Funciones)
        MyBase.AddObject("Funciones", funciones)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Inasistencias. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToInasistencias(ByVal inasistencias As Inasistencias)
        MyBase.AddObject("Inasistencias", inasistencias)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Personas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToPersonas(ByVal personas As Personas)
        MyBase.AddObject("Personas", personas)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet PersonasTel. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToPersonasTel(ByVal personasTel As PersonasTel)
        MyBase.AddObject("PersonasTel", personasTel)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet SituacionesProfesionales. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToSituacionesProfesionales(ByVal situacionesProfesionales As SituacionesProfesionales)
        MyBase.AddObject("SituacionesProfesionales", situacionesProfesionales)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToUsuarios(ByVal usuarios As Usuarios)
        MyBase.AddObject("Usuarios", usuarios)
    End Sub

    #End Region

End Class

#End Region

#Region "Entidades"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Contratos")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Contratos
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Contratos.
    ''' </summary>
    ''' <param name="id">Valor inicial de la propiedad Id.</param>
    ''' <param name="personaId">Valor inicial de la propiedad PersonaId.</param>
    ''' <param name="fechaInicio">Valor inicial de la propiedad FechaInicio.</param>
    ''' <param name="afectado">Valor inicial de la propiedad Afectado.</param>
    ''' <param name="origen">Valor inicial de la propiedad Origen.</param>
    ''' <param name="cargoId">Valor inicial de la propiedad CargoId.</param>
    ''' <param name="condicionId">Valor inicial de la propiedad CondicionId.</param>
    ''' <param name="funcionId">Valor inicial de la propiedad FuncionId.</param>
    ''' <param name="equipoId">Valor inicial de la propiedad EquipoId.</param>
    ''' <param name="horas">Valor inicial de la propiedad Horas.</param>
    Public Shared Function CreateContratos(id As Global.System.Int32, personaId As Global.System.Int32, fechaInicio As Global.System.DateTime, afectado As Global.System.Boolean, origen As Global.System.String, cargoId As Global.System.String, condicionId As Global.System.String, funcionId As Global.System.String, equipoId As Global.System.String, horas As Global.System.Byte) As Contratos
        Dim contratos as Contratos = New Contratos
        contratos.Id = id
        contratos.PersonaId = personaId
        contratos.FechaInicio = fechaInicio
        contratos.Afectado = afectado
        contratos.Origen = origen
        contratos.CargoId = cargoId
        contratos.CondicionId = condicionId
        contratos.FuncionId = funcionId
        contratos.EquipoId = equipoId
        contratos.Horas = horas
        Return contratos
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PersonaId() As Global.System.Int32
        Get
            Return _PersonaId
        End Get
        Set
            OnPersonaIdChanging(value)
            ReportPropertyChanging("PersonaId")
            _PersonaId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PersonaId")
            OnPersonaIdChanged()
        End Set
    End Property

    Private _PersonaId As Global.System.Int32
    Private Partial Sub OnPersonaIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnPersonaIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FechaInicio() As Global.System.DateTime
        Get
            Return _FechaInicio
        End Get
        Set
            OnFechaInicioChanging(value)
            ReportPropertyChanging("FechaInicio")
            _FechaInicio = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FechaInicio")
            OnFechaInicioChanged()
        End Set
    End Property

    Private _FechaInicio As Global.System.DateTime
    Private Partial Sub OnFechaInicioChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnFechaInicioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FechaBaja() As Nullable(Of Global.System.DateTime)
        Get
            Return _FechaBaja
        End Get
        Set
            OnFechaBajaChanging(value)
            ReportPropertyChanging("FechaBaja")
            _FechaBaja = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FechaBaja")
            OnFechaBajaChanged()
        End Set
    End Property

    Private _FechaBaja As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnFechaBajaChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnFechaBajaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Afectado() As Global.System.Boolean
        Get
            Return _Afectado
        End Get
        Set
            OnAfectadoChanging(value)
            ReportPropertyChanging("Afectado")
            _Afectado = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Afectado")
            OnAfectadoChanged()
        End Set
    End Property

    Private _Afectado As Global.System.Boolean
    Private Partial Sub OnAfectadoChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnAfectadoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Origen() As Global.System.String
        Get
            Return _Origen
        End Get
        Set
            OnOrigenChanging(value)
            ReportPropertyChanging("Origen")
            _Origen = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Origen")
            OnOrigenChanged()
        End Set
    End Property

    Private _Origen As Global.System.String
    Private Partial Sub OnOrigenChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnOrigenChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CargoId() As Global.System.String
        Get
            Return _CargoId
        End Get
        Set
            OnCargoIdChanging(value)
            ReportPropertyChanging("CargoId")
            _CargoId = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("CargoId")
            OnCargoIdChanged()
        End Set
    End Property

    Private _CargoId As Global.System.String
    Private Partial Sub OnCargoIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCargoIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CondicionId() As Global.System.String
        Get
            Return _CondicionId
        End Get
        Set
            OnCondicionIdChanging(value)
            ReportPropertyChanging("CondicionId")
            _CondicionId = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("CondicionId")
            OnCondicionIdChanged()
        End Set
    End Property

    Private _CondicionId As Global.System.String
    Private Partial Sub OnCondicionIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCondicionIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FuncionId() As Global.System.String
        Get
            Return _FuncionId
        End Get
        Set
            OnFuncionIdChanging(value)
            ReportPropertyChanging("FuncionId")
            _FuncionId = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("FuncionId")
            OnFuncionIdChanged()
        End Set
    End Property

    Private _FuncionId As Global.System.String
    Private Partial Sub OnFuncionIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFuncionIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property EquipoId() As Global.System.String
        Get
            Return _EquipoId
        End Get
        Set
            OnEquipoIdChanging(value)
            ReportPropertyChanging("EquipoId")
            _EquipoId = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("EquipoId")
            OnEquipoIdChanged()
        End Set
    End Property

    Private _EquipoId As Global.System.String
    Private Partial Sub OnEquipoIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEquipoIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Horas() As Global.System.Byte
        Get
            Return _Horas
        End Get
        Set
            OnHorasChanging(value)
            ReportPropertyChanging("Horas")
            _Horas = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Horas")
            OnHorasChanged()
        End Set
    End Property

    Private _Horas As Global.System.Byte
    Private Partial Sub OnHorasChanging(value As Global.System.Byte)
    End Sub

    Private Partial Sub OnHorasChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Observacion() As Global.System.String
        Get
            Return _Observacion
        End Get
        Set
            OnObservacionChanging(value)
            ReportPropertyChanging("Observacion")
            _Observacion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Observacion")
            OnObservacionChanged()
        End Set
    End Property

    Private _Observacion As Global.System.String
    Private Partial Sub OnObservacionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnObservacionChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Equipos_Contratos", "Equipos")>
    Public Property Equipos() As Equipos
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Equipos)("CSAdminBDModel.Equipos_Contratos", "Equipos").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Equipos)("CSAdminBDModel.Equipos_Contratos", "Equipos").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property EquiposReference() As EntityReference(Of Equipos)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Equipos)("CSAdminBDModel.Equipos_Contratos", "Equipos")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Equipos)("CSAdminBDModel.Equipos_Contratos", "Equipos", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Funciones_Contratos", "Funciones")>
    Public Property Funciones() As Funciones
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Funciones)("CSAdminBDModel.Funciones_Contratos", "Funciones").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Funciones)("CSAdminBDModel.Funciones_Contratos", "Funciones").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property FuncionesReference() As EntityReference(Of Funciones)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Funciones)("CSAdminBDModel.Funciones_Contratos", "Funciones")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Funciones)("CSAdminBDModel.Funciones_Contratos", "Funciones", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Contratos", "Personas")>
    Public Property Personas() As Personas
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Contratos", "Personas").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Contratos", "Personas").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PersonasReference() As EntityReference(Of Personas)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Contratos", "Personas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personas)("CSAdminBDModel.Personas_Contratos", "Personas", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "SituacionesProfesionales_Contratos", "SituacionesProfesionales")>
    Public Property SituacionesProfesionales() As SituacionesProfesionales
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SituacionesProfesionales)("CSAdminBDModel.SituacionesProfesionales_Contratos", "SituacionesProfesionales").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SituacionesProfesionales)("CSAdminBDModel.SituacionesProfesionales_Contratos", "SituacionesProfesionales").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SituacionesProfesionalesReference() As EntityReference(Of SituacionesProfesionales)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SituacionesProfesionales)("CSAdminBDModel.SituacionesProfesionales_Contratos", "SituacionesProfesionales")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SituacionesProfesionales)("CSAdminBDModel.SituacionesProfesionales_Contratos", "SituacionesProfesionales", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Equipos")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Equipos
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Equipos.
    ''' </summary>
    ''' <param name="id">Valor inicial de la propiedad Id.</param>
    ''' <param name="ubicacion">Valor inicial de la propiedad Ubicacion.</param>
    ''' <param name="localidad">Valor inicial de la propiedad Localidad.</param>
    ''' <param name="coordinadorId">Valor inicial de la propiedad CoordinadorId.</param>
    Public Shared Function CreateEquipos(id As Global.System.String, ubicacion As Global.System.String, localidad As Global.System.String, coordinadorId As Global.System.Int32) As Equipos
        Dim equipos as Equipos = New Equipos
        equipos.Id = id
        equipos.Ubicacion = ubicacion
        equipos.Localidad = localidad
        equipos.CoordinadorId = coordinadorId
        Return equipos
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.String
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.String
    Private Partial Sub OnIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Ubicacion() As Global.System.String
        Get
            Return _Ubicacion
        End Get
        Set
            OnUbicacionChanging(value)
            ReportPropertyChanging("Ubicacion")
            _Ubicacion = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Ubicacion")
            OnUbicacionChanged()
        End Set
    End Property

    Private _Ubicacion As Global.System.String
    Private Partial Sub OnUbicacionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUbicacionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Localidad() As Global.System.String
        Get
            Return _Localidad
        End Get
        Set
            OnLocalidadChanging(value)
            ReportPropertyChanging("Localidad")
            _Localidad = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Localidad")
            OnLocalidadChanged()
        End Set
    End Property

    Private _Localidad As Global.System.String
    Private Partial Sub OnLocalidadChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLocalidadChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Correo() As Global.System.String
        Get
            Return _Correo
        End Get
        Set
            OnCorreoChanging(value)
            ReportPropertyChanging("Correo")
            _Correo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Correo")
            OnCorreoChanged()
        End Set
    End Property

    Private _Correo As Global.System.String
    Private Partial Sub OnCorreoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCorreoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Telefono() As Nullable(Of Global.System.Decimal)
        Get
            Return _Telefono
        End Get
        Set
            OnTelefonoChanging(value)
            ReportPropertyChanging("Telefono")
            _Telefono = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Telefono")
            OnTelefonoChanged()
        End Set
    End Property

    Private _Telefono As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnTelefonoChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnTelefonoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CoordinadorId() As Global.System.Int32
        Get
            Return _CoordinadorId
        End Get
        Set
            OnCoordinadorIdChanging(value)
            ReportPropertyChanging("CoordinadorId")
            _CoordinadorId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CoordinadorId")
            OnCoordinadorIdChanged()
        End Set
    End Property

    Private _CoordinadorId As Global.System.Int32
    Private Partial Sub OnCoordinadorIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCoordinadorIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Contra() As Global.System.String
        Get
            Return _Contra
        End Get
        Set
            OnContraChanging(value)
            ReportPropertyChanging("Contra")
            _Contra = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Contra")
            OnContraChanged()
        End Set
    End Property

    Private _Contra As Global.System.String
    Private Partial Sub OnContraChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnContraChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Equipos_Contratos", "Contratos")>
     Public Property Contratos() As EntityCollection(Of Contratos)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Contratos)("CSAdminBDModel.Equipos_Contratos", "Contratos")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Contratos)("CSAdminBDModel.Equipos_Contratos", "Contratos", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Equipos", "Personas")>
    Public Property Personas() As Personas
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Equipos", "Personas").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Equipos", "Personas").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PersonasReference() As EntityReference(Of Personas)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Equipos", "Personas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personas)("CSAdminBDModel.Personas_Equipos", "Personas", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Funciones")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Funciones
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Funciones.
    ''' </summary>
    ''' <param name="id">Valor inicial de la propiedad Id.</param>
    ''' <param name="funcion">Valor inicial de la propiedad Funcion.</param>
    Public Shared Function CreateFunciones(id As Global.System.String, funcion As Global.System.String) As Funciones
        Dim funciones as Funciones = New Funciones
        funciones.Id = id
        funciones.Funcion = funcion
        Return funciones
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.String
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.String
    Private Partial Sub OnIdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Funcion() As Global.System.String
        Get
            Return _Funcion
        End Get
        Set
            OnFuncionChanging(value)
            ReportPropertyChanging("Funcion")
            _Funcion = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Funcion")
            OnFuncionChanged()
        End Set
    End Property

    Private _Funcion As Global.System.String
    Private Partial Sub OnFuncionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFuncionChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Funciones_Contratos", "Contratos")>
     Public Property Contratos() As EntityCollection(Of Contratos)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Contratos)("CSAdminBDModel.Funciones_Contratos", "Contratos")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Contratos)("CSAdminBDModel.Funciones_Contratos", "Contratos", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Inasistencias")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Inasistencias
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Inasistencias.
    ''' </summary>
    ''' <param name="id">Valor inicial de la propiedad Id.</param>
    ''' <param name="idPersona">Valor inicial de la propiedad IdPersona.</param>
    ''' <param name="desde">Valor inicial de la propiedad Desde.</param>
    ''' <param name="hasta">Valor inicial de la propiedad Hasta.</param>
    Public Shared Function CreateInasistencias(id As Global.System.Int32, idPersona As Global.System.Int32, desde As Global.System.DateTime, hasta As Global.System.DateTime) As Inasistencias
        Dim inasistencias as Inasistencias = New Inasistencias
        inasistencias.Id = id
        inasistencias.IdPersona = idPersona
        inasistencias.Desde = desde
        inasistencias.Hasta = hasta
        Return inasistencias
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IdPersona() As Global.System.Int32
        Get
            Return _IdPersona
        End Get
        Set
            If (_IdPersona <> Value) Then
                OnIdPersonaChanging(value)
                ReportPropertyChanging("IdPersona")
                _IdPersona = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IdPersona")
                OnIdPersonaChanged()
            End If
        End Set
    End Property

    Private _IdPersona As Global.System.Int32
    Private Partial Sub OnIdPersonaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdPersonaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Desde() As Global.System.DateTime
        Get
            Return _Desde
        End Get
        Set
            OnDesdeChanging(value)
            ReportPropertyChanging("Desde")
            _Desde = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Desde")
            OnDesdeChanged()
        End Set
    End Property

    Private _Desde As Global.System.DateTime
    Private Partial Sub OnDesdeChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDesdeChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Hasta() As Global.System.DateTime
        Get
            Return _Hasta
        End Get
        Set
            OnHastaChanging(value)
            ReportPropertyChanging("Hasta")
            _Hasta = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Hasta")
            OnHastaChanged()
        End Set
    End Property

    Private _Hasta As Global.System.DateTime
    Private Partial Sub OnHastaChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnHastaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Motivo() As Global.System.String
        Get
            Return _Motivo
        End Get
        Set
            OnMotivoChanging(value)
            ReportPropertyChanging("Motivo")
            _Motivo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Motivo")
            OnMotivoChanged()
        End Set
    End Property

    Private _Motivo As Global.System.String
    Private Partial Sub OnMotivoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMotivoChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Inasistencias", "Personas")>
    Public Property Personas() As Personas
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Inasistencias", "Personas").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Inasistencias", "Personas").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PersonasReference() As EntityReference(Of Personas)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Inasistencias", "Personas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personas)("CSAdminBDModel.Personas_Inasistencias", "Personas", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Personas")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Personas
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Personas.
    ''' </summary>
    ''' <param name="id">Valor inicial de la propiedad ID.</param>
    ''' <param name="dNI">Valor inicial de la propiedad DNI.</param>
    ''' <param name="nombre">Valor inicial de la propiedad Nombre.</param>
    ''' <param name="apellido">Valor inicial de la propiedad Apellido.</param>
    ''' <param name="baja">Valor inicial de la propiedad Baja.</param>
    Public Shared Function CreatePersonas(id As Global.System.Int32, dNI As Global.System.Decimal, nombre As Global.System.String, apellido As Global.System.String, baja As Global.System.Boolean) As Personas
        Dim personas as Personas = New Personas
        personas.ID = id
        personas.DNI = dNI
        personas.Nombre = nombre
        personas.Apellido = apellido
        personas.Baja = baja
        Return personas
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DNI() As Global.System.Decimal
        Get
            Return _DNI
        End Get
        Set
            OnDNIChanging(value)
            ReportPropertyChanging("DNI")
            _DNI = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DNI")
            OnDNIChanged()
        End Set
    End Property

    Private _DNI As Global.System.Decimal
    Private Partial Sub OnDNIChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnDNIChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CUIT() As Nullable(Of Global.System.Decimal)
        Get
            Return _CUIT
        End Get
        Set
            OnCUITChanging(value)
            ReportPropertyChanging("CUIT")
            _CUIT = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CUIT")
            OnCUITChanged()
        End Set
    End Property

    Private _CUIT As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnCUITChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnCUITChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Nombre() As Global.System.String
        Get
            Return _Nombre
        End Get
        Set
            OnNombreChanging(value)
            ReportPropertyChanging("Nombre")
            _Nombre = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Nombre")
            OnNombreChanged()
        End Set
    End Property

    Private _Nombre As Global.System.String
    Private Partial Sub OnNombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNombreChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Apellido() As Global.System.String
        Get
            Return _Apellido
        End Get
        Set
            OnApellidoChanging(value)
            ReportPropertyChanging("Apellido")
            _Apellido = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Apellido")
            OnApellidoChanged()
        End Set
    End Property

    Private _Apellido As Global.System.String
    Private Partial Sub OnApellidoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnApellidoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Direccion() As Global.System.String
        Get
            Return _Direccion
        End Get
        Set
            OnDireccionChanging(value)
            ReportPropertyChanging("Direccion")
            _Direccion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Direccion")
            OnDireccionChanged()
        End Set
    End Property

    Private _Direccion As Global.System.String
    Private Partial Sub OnDireccionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDireccionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Correo() As Global.System.String
        Get
            Return _Correo
        End Get
        Set
            OnCorreoChanging(value)
            ReportPropertyChanging("Correo")
            _Correo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Correo")
            OnCorreoChanged()
        End Set
    End Property

    Private _Correo As Global.System.String
    Private Partial Sub OnCorreoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCorreoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Baja() As Global.System.Boolean
        Get
            Return _Baja
        End Get
        Set
            OnBajaChanging(value)
            ReportPropertyChanging("Baja")
            _Baja = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Baja")
            OnBajaChanged()
        End Set
    End Property

    Private _Baja As Global.System.Boolean
    Private Partial Sub OnBajaChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnBajaChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Contratos", "Contratos")>
     Public Property Contratos() As EntityCollection(Of Contratos)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Contratos)("CSAdminBDModel.Personas_Contratos", "Contratos")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Contratos)("CSAdminBDModel.Personas_Contratos", "Contratos", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Equipos", "Equipos")>
     Public Property Equipos() As EntityCollection(Of Equipos)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Equipos)("CSAdminBDModel.Personas_Equipos", "Equipos")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Equipos)("CSAdminBDModel.Personas_Equipos", "Equipos", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Inasistencias", "Inasistencias")>
     Public Property Inasistencias() As EntityCollection(Of Inasistencias)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Inasistencias)("CSAdminBDModel.Personas_Inasistencias", "Inasistencias")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Inasistencias)("CSAdminBDModel.Personas_Inasistencias", "Inasistencias", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_PersonasTel", "PersonasTel")>
     Public Property PersonasTel() As EntityCollection(Of PersonasTel)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of PersonasTel)("CSAdminBDModel.Personas_PersonasTel", "PersonasTel")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of PersonasTel)("CSAdminBDModel.Personas_PersonasTel", "PersonasTel", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Usuarios", "Usuarios")>
     Public Property Usuarios() As EntityCollection(Of Usuarios)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Usuarios)("CSAdminBDModel.Personas_Usuarios", "Usuarios")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Usuarios)("CSAdminBDModel.Personas_Usuarios", "Usuarios", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="PersonasTel")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class PersonasTel
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto PersonasTel.
    ''' </summary>
    ''' <param name="idPersona">Valor inicial de la propiedad IdPersona.</param>
    ''' <param name="tipo">Valor inicial de la propiedad Tipo.</param>
    ''' <param name="numero">Valor inicial de la propiedad Numero.</param>
    Public Shared Function CreatePersonasTel(idPersona As Global.System.Int32, tipo As Global.System.String, numero As Global.System.Decimal) As PersonasTel
        Dim personasTel as PersonasTel = New PersonasTel
        personasTel.IdPersona = idPersona
        personasTel.Tipo = tipo
        personasTel.Numero = numero
        Return personasTel
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IdPersona() As Global.System.Int32
        Get
            Return _IdPersona
        End Get
        Set
            If (_IdPersona <> Value) Then
                OnIdPersonaChanging(value)
                ReportPropertyChanging("IdPersona")
                _IdPersona = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IdPersona")
                OnIdPersonaChanged()
            End If
        End Set
    End Property

    Private _IdPersona As Global.System.Int32
    Private Partial Sub OnIdPersonaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdPersonaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Tipo() As Global.System.String
        Get
            Return _Tipo
        End Get
        Set
            If (_Tipo <> Value) Then
                OnTipoChanging(value)
                ReportPropertyChanging("Tipo")
                _Tipo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Tipo")
                OnTipoChanged()
            End If
        End Set
    End Property

    Private _Tipo As Global.System.String
    Private Partial Sub OnTipoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTipoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Numero() As Global.System.Decimal
        Get
            Return _Numero
        End Get
        Set
            OnNumeroChanging(value)
            ReportPropertyChanging("Numero")
            _Numero = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Numero")
            OnNumeroChanged()
        End Set
    End Property

    Private _Numero As Global.System.Decimal
    Private Partial Sub OnNumeroChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnNumeroChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_PersonasTel", "Personas")>
    Public Property Personas() As Personas
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_PersonasTel", "Personas").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_PersonasTel", "Personas").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PersonasReference() As EntityReference(Of Personas)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_PersonasTel", "Personas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personas)("CSAdminBDModel.Personas_PersonasTel", "Personas", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="SituacionesProfesionales")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SituacionesProfesionales
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto SituacionesProfesionales.
    ''' </summary>
    ''' <param name="cargoAbrev">Valor inicial de la propiedad CargoAbrev.</param>
    ''' <param name="cargo">Valor inicial de la propiedad Cargo.</param>
    ''' <param name="condicionAbrev">Valor inicial de la propiedad CondicionAbrev.</param>
    ''' <param name="condicion">Valor inicial de la propiedad Condicion.</param>
    Public Shared Function CreateSituacionesProfesionales(cargoAbrev As Global.System.String, cargo As Global.System.String, condicionAbrev As Global.System.String, condicion As Global.System.String) As SituacionesProfesionales
        Dim situacionesProfesionales as SituacionesProfesionales = New SituacionesProfesionales
        situacionesProfesionales.CargoAbrev = cargoAbrev
        situacionesProfesionales.Cargo = cargo
        situacionesProfesionales.CondicionAbrev = condicionAbrev
        situacionesProfesionales.Condicion = condicion
        Return situacionesProfesionales
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CargoAbrev() As Global.System.String
        Get
            Return _CargoAbrev
        End Get
        Set
            If (_CargoAbrev <> Value) Then
                OnCargoAbrevChanging(value)
                ReportPropertyChanging("CargoAbrev")
                _CargoAbrev = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CargoAbrev")
                OnCargoAbrevChanged()
            End If
        End Set
    End Property

    Private _CargoAbrev As Global.System.String
    Private Partial Sub OnCargoAbrevChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCargoAbrevChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Cargo() As Global.System.String
        Get
            Return _Cargo
        End Get
        Set
            OnCargoChanging(value)
            ReportPropertyChanging("Cargo")
            _Cargo = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Cargo")
            OnCargoChanged()
        End Set
    End Property

    Private _Cargo As Global.System.String
    Private Partial Sub OnCargoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCargoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CondicionAbrev() As Global.System.String
        Get
            Return _CondicionAbrev
        End Get
        Set
            If (_CondicionAbrev <> Value) Then
                OnCondicionAbrevChanging(value)
                ReportPropertyChanging("CondicionAbrev")
                _CondicionAbrev = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CondicionAbrev")
                OnCondicionAbrevChanged()
            End If
        End Set
    End Property

    Private _CondicionAbrev As Global.System.String
    Private Partial Sub OnCondicionAbrevChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCondicionAbrevChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Condicion() As Global.System.String
        Get
            Return _Condicion
        End Get
        Set
            OnCondicionChanging(value)
            ReportPropertyChanging("Condicion")
            _Condicion = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Condicion")
            OnCondicionChanged()
        End Set
    End Property

    Private _Condicion As Global.System.String
    Private Partial Sub OnCondicionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCondicionChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "SituacionesProfesionales_Contratos", "Contratos")>
     Public Property Contratos() As EntityCollection(Of Contratos)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Contratos)("CSAdminBDModel.SituacionesProfesionales_Contratos", "Contratos")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Contratos)("CSAdminBDModel.SituacionesProfesionales_Contratos", "Contratos", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Usuarios")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Usuarios
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Usuarios.
    ''' </summary>
    ''' <param name="usuario">Valor inicial de la propiedad Usuario.</param>
    ''' <param name="contra">Valor inicial de la propiedad Contra.</param>
    ''' <param name="rol">Valor inicial de la propiedad Rol.</param>
    ''' <param name="personaId">Valor inicial de la propiedad PersonaId.</param>
    Public Shared Function CreateUsuarios(usuario As Global.System.String, contra As Global.System.String, rol As Global.System.String, personaId As Global.System.Int32) As Usuarios
        Dim usuarios as Usuarios = New Usuarios
        usuarios.Usuario = usuario
        usuarios.Contra = contra
        usuarios.Rol = rol
        usuarios.PersonaId = personaId
        Return usuarios
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Usuario() As Global.System.String
        Get
            Return _Usuario
        End Get
        Set
            If (_Usuario <> Value) Then
                OnUsuarioChanging(value)
                ReportPropertyChanging("Usuario")
                _Usuario = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Usuario")
                OnUsuarioChanged()
            End If
        End Set
    End Property

    Private _Usuario As Global.System.String
    Private Partial Sub OnUsuarioChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUsuarioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Contra() As Global.System.String
        Get
            Return _Contra
        End Get
        Set
            OnContraChanging(value)
            ReportPropertyChanging("Contra")
            _Contra = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Contra")
            OnContraChanged()
        End Set
    End Property

    Private _Contra As Global.System.String
    Private Partial Sub OnContraChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnContraChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Rol() As Global.System.String
        Get
            Return _Rol
        End Get
        Set
            OnRolChanging(value)
            ReportPropertyChanging("Rol")
            _Rol = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Rol")
            OnRolChanged()
        End Set
    End Property

    Private _Rol As Global.System.String
    Private Partial Sub OnRolChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRolChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PersonaId() As Global.System.Int32
        Get
            Return _PersonaId
        End Get
        Set
            OnPersonaIdChanging(value)
            ReportPropertyChanging("PersonaId")
            _PersonaId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PersonaId")
            OnPersonaIdChanged()
        End Set
    End Property

    Private _PersonaId As Global.System.Int32
    Private Partial Sub OnPersonaIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnPersonaIdChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Usuarios", "Personas")>
    Public Property Personas() As Personas
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Usuarios", "Personas").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Usuarios", "Personas").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PersonasReference() As EntityReference(Of Personas)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Usuarios", "Personas")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personas)("CSAdminBDModel.Personas_Usuarios", "Personas", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


