'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4984
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("e452ce60-aaec-4b44-9b43-a06ce52a1d1f"),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSAdminBDModel", "Equipos_Contratos", "Equipos", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Equipos), "Contratos", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Contratos)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSAdminBDModel", "Funciones_Contratos", "Funciones", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Funciones), "Contratos", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Contratos)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSAdminBDModel", "Personas_Contratos", "Personas", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Personas), "Contratos", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Contratos)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSAdminBDModel", "SituacionesProfesionales_Contratos", "SituacionesProfesionales", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SituacionesProfesionales), "Contratos", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Contratos)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSAdminBDModel", "Personas_Equipos", "Personas", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Personas), "Equipos", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Equipos)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSAdminBDModel", "Personas_Inasistencias", "Personas", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Personas), "Inasistencias", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Inasistencias)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSAdminBDModel", "Personas_PersonasTel", "Personas", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Personas), "PersonasTel", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(PersonasTel)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSAdminBDModel", "Usuarios_Personas", "Personas", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Personas), "Usuarios", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Usuarios))> 

'Original file name:
'Generation date: 20/02/2014 11:54:06 a.m.
'''<summary>
'''There are no comments for CSAdminBDEntities1 in the schema.
'''</summary>
Partial Public Class CSAdminBDEntities1
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new CSAdminBDEntities1 object using the connection string found in the 'CSAdminBDEntities1' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=CSAdminBDEntities1", "CSAdminBDEntities1")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new CSAdminBDEntities1 object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "CSAdminBDEntities1")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new CSAdminBDEntities1 object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "CSAdminBDEntities1")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for Contratos in the schema.
    '''</summary>
    Public ReadOnly Property Contratos() As Global.System.Data.Objects.ObjectQuery(Of Contratos)
        Get
            If (Me._Contratos Is Nothing) Then
                Me._Contratos = MyBase.CreateQuery(Of Contratos)("[Contratos]")
            End If
            Return Me._Contratos
        End Get
    End Property
    Private _Contratos As Global.System.Data.Objects.ObjectQuery(Of Contratos)
    '''<summary>
    '''There are no comments for Equipos in the schema.
    '''</summary>
    Public ReadOnly Property Equipos() As Global.System.Data.Objects.ObjectQuery(Of Equipos)
        Get
            If (Me._Equipos Is Nothing) Then
                Me._Equipos = MyBase.CreateQuery(Of Equipos)("[Equipos]")
            End If
            Return Me._Equipos
        End Get
    End Property
    Private _Equipos As Global.System.Data.Objects.ObjectQuery(Of Equipos)
    '''<summary>
    '''There are no comments for Funciones in the schema.
    '''</summary>
    Public ReadOnly Property Funciones() As Global.System.Data.Objects.ObjectQuery(Of Funciones)
        Get
            If (Me._Funciones Is Nothing) Then
                Me._Funciones = MyBase.CreateQuery(Of Funciones)("[Funciones]")
            End If
            Return Me._Funciones
        End Get
    End Property
    Private _Funciones As Global.System.Data.Objects.ObjectQuery(Of Funciones)
    '''<summary>
    '''There are no comments for Inasistencias in the schema.
    '''</summary>
    Public ReadOnly Property Inasistencias() As Global.System.Data.Objects.ObjectQuery(Of Inasistencias)
        Get
            If (Me._Inasistencias Is Nothing) Then
                Me._Inasistencias = MyBase.CreateQuery(Of Inasistencias)("[Inasistencias]")
            End If
            Return Me._Inasistencias
        End Get
    End Property
    Private _Inasistencias As Global.System.Data.Objects.ObjectQuery(Of Inasistencias)
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    Public ReadOnly Property Personas() As Global.System.Data.Objects.ObjectQuery(Of Personas)
        Get
            If (Me._Personas Is Nothing) Then
                Me._Personas = MyBase.CreateQuery(Of Personas)("[Personas]")
            End If
            Return Me._Personas
        End Get
    End Property
    Private _Personas As Global.System.Data.Objects.ObjectQuery(Of Personas)
    '''<summary>
    '''There are no comments for PersonasTel in the schema.
    '''</summary>
    Public ReadOnly Property PersonasTel() As Global.System.Data.Objects.ObjectQuery(Of PersonasTel)
        Get
            If (Me._PersonasTel Is Nothing) Then
                Me._PersonasTel = MyBase.CreateQuery(Of PersonasTel)("[PersonasTel]")
            End If
            Return Me._PersonasTel
        End Get
    End Property
    Private _PersonasTel As Global.System.Data.Objects.ObjectQuery(Of PersonasTel)
    '''<summary>
    '''There are no comments for SituacionesProfesionales in the schema.
    '''</summary>
    Public ReadOnly Property SituacionesProfesionales() As Global.System.Data.Objects.ObjectQuery(Of SituacionesProfesionales)
        Get
            If (Me._SituacionesProfesionales Is Nothing) Then
                Me._SituacionesProfesionales = MyBase.CreateQuery(Of SituacionesProfesionales)("[SituacionesProfesionales]")
            End If
            Return Me._SituacionesProfesionales
        End Get
    End Property
    Private _SituacionesProfesionales As Global.System.Data.Objects.ObjectQuery(Of SituacionesProfesionales)
    '''<summary>
    '''There are no comments for Usuarios in the schema.
    '''</summary>
    Public ReadOnly Property Usuarios() As Global.System.Data.Objects.ObjectQuery(Of Usuarios)
        Get
            If (Me._Usuarios Is Nothing) Then
                Me._Usuarios = MyBase.CreateQuery(Of Usuarios)("[Usuarios]")
            End If
            Return Me._Usuarios
        End Get
    End Property
    Private _Usuarios As Global.System.Data.Objects.ObjectQuery(Of Usuarios)
    '''<summary>
    '''There are no comments for Contratos in the schema.
    '''</summary>
    Public Sub AddToContratos(ByVal contratos As Contratos)
        MyBase.AddObject("Contratos", contratos)
    End Sub
    '''<summary>
    '''There are no comments for Equipos in the schema.
    '''</summary>
    Public Sub AddToEquipos(ByVal equipos As Equipos)
        MyBase.AddObject("Equipos", equipos)
    End Sub
    '''<summary>
    '''There are no comments for Funciones in the schema.
    '''</summary>
    Public Sub AddToFunciones(ByVal funciones As Funciones)
        MyBase.AddObject("Funciones", funciones)
    End Sub
    '''<summary>
    '''There are no comments for Inasistencias in the schema.
    '''</summary>
    Public Sub AddToInasistencias(ByVal inasistencias As Inasistencias)
        MyBase.AddObject("Inasistencias", inasistencias)
    End Sub
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    Public Sub AddToPersonas(ByVal personas As Personas)
        MyBase.AddObject("Personas", personas)
    End Sub
    '''<summary>
    '''There are no comments for PersonasTel in the schema.
    '''</summary>
    Public Sub AddToPersonasTel(ByVal personasTel As PersonasTel)
        MyBase.AddObject("PersonasTel", personasTel)
    End Sub
    '''<summary>
    '''There are no comments for SituacionesProfesionales in the schema.
    '''</summary>
    Public Sub AddToSituacionesProfesionales(ByVal situacionesProfesionales As SituacionesProfesionales)
        MyBase.AddObject("SituacionesProfesionales", situacionesProfesionales)
    End Sub
    '''<summary>
    '''There are no comments for Usuarios in the schema.
    '''</summary>
    Public Sub AddToUsuarios(ByVal usuarios As Usuarios)
        MyBase.AddObject("Usuarios", usuarios)
    End Sub
End Class
'''<summary>
'''There are no comments for CSAdminBDModel.Contratos in the schema.
'''</summary>
'''<KeyProperties>
'''Id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Contratos"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Contratos
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Contratos object.
    '''</summary>
    '''<param name="id">Initial value of Id.</param>
    '''<param name="fechaInicio">Initial value of FechaInicio.</param>
    '''<param name="afectado">Initial value of Afectado.</param>
    '''<param name="origen">Initial value of Origen.</param>
    '''<param name="horas">Initial value of Horas.</param>
    Public Shared Function CreateContratos(ByVal id As Integer, ByVal fechaInicio As Date, ByVal afectado As Boolean, ByVal origen As String, ByVal horas As Byte) As Contratos
        Dim contratos As Contratos = New Contratos
        contratos.Id = id
        contratos.FechaInicio = fechaInicio
        contratos.Afectado = afectado
        contratos.Origen = origen
        contratos.Horas = horas
        Return contratos
    End Function
    '''<summary>
    '''There are no comments for Property Id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Id() As Integer
        Get
            Return Me._Id
        End Get
        Set
            Me.OnIdChanging(value)
            Me.ReportPropertyChanging("Id")
            Me._Id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Id")
            Me.OnIdChanged
        End Set
    End Property
    Private _Id As Integer
    Partial Private Sub OnIdChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIdChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property FechaInicio in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property FechaInicio() As Date
        Get
            Return Me._FechaInicio
        End Get
        Set
            Me.OnFechaInicioChanging(value)
            Me.ReportPropertyChanging("FechaInicio")
            Me._FechaInicio = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("FechaInicio")
            Me.OnFechaInicioChanged
        End Set
    End Property
    Private _FechaInicio As Date
    Partial Private Sub OnFechaInicioChanging(ByVal value As Date)
        End Sub
    Partial Private Sub OnFechaInicioChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property FechaBaja in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property FechaBaja() As Global.System.Nullable(Of Date)
        Get
            Return Me._FechaBaja
        End Get
        Set
            Me.OnFechaBajaChanging(value)
            Me.ReportPropertyChanging("FechaBaja")
            Me._FechaBaja = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("FechaBaja")
            Me.OnFechaBajaChanged
        End Set
    End Property
    Private _FechaBaja As Global.System.Nullable(Of Date)
    Partial Private Sub OnFechaBajaChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    Partial Private Sub OnFechaBajaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Afectado in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Afectado() As Boolean
        Get
            Return Me._Afectado
        End Get
        Set
            Me.OnAfectadoChanging(value)
            Me.ReportPropertyChanging("Afectado")
            Me._Afectado = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Afectado")
            Me.OnAfectadoChanged
        End Set
    End Property
    Private _Afectado As Boolean
    Partial Private Sub OnAfectadoChanging(ByVal value As Boolean)
        End Sub
    Partial Private Sub OnAfectadoChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Origen in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Origen() As String
        Get
            Return Me._Origen
        End Get
        Set
            Me.OnOrigenChanging(value)
            Me.ReportPropertyChanging("Origen")
            Me._Origen = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Origen")
            Me.OnOrigenChanged
        End Set
    End Property
    Private _Origen As String
    Partial Private Sub OnOrigenChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnOrigenChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Horas in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Horas() As Byte
        Get
            Return Me._Horas
        End Get
        Set
            Me.OnHorasChanging(value)
            Me.ReportPropertyChanging("Horas")
            Me._Horas = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Horas")
            Me.OnHorasChanged
        End Set
    End Property
    Private _Horas As Byte
    Partial Private Sub OnHorasChanging(ByVal value As Byte)
        End Sub
    Partial Private Sub OnHorasChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Observacion in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Observacion() As String
        Get
            Return Me._Observacion
        End Get
        Set
            Me.OnObservacionChanging(value)
            Me.ReportPropertyChanging("Observacion")
            Me._Observacion = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Observacion")
            Me.OnObservacionChanged
        End Set
    End Property
    Private _Observacion As String
    Partial Private Sub OnObservacionChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnObservacionChanged()
        End Sub
    '''<summary>
    '''There are no comments for Equipos in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Equipos_Contratos", "Equipos"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Equipos() As Equipos
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Equipos)("CSAdminBDModel.Equipos_Contratos", "Equipos").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Equipos)("CSAdminBDModel.Equipos_Contratos", "Equipos").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Equipos in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property EquiposReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Equipos)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Equipos)("CSAdminBDModel.Equipos_Contratos", "Equipos")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Equipos)("CSAdminBDModel.Equipos_Contratos", "Equipos", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Funciones in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Funciones_Contratos", "Funciones"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Funciones() As Funciones
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Funciones)("CSAdminBDModel.Funciones_Contratos", "Funciones").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Funciones)("CSAdminBDModel.Funciones_Contratos", "Funciones").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Funciones in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property FuncionesReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Funciones)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Funciones)("CSAdminBDModel.Funciones_Contratos", "Funciones")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Funciones)("CSAdminBDModel.Funciones_Contratos", "Funciones", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Contratos", "Personas"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Personas() As Personas
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Contratos", "Personas").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Contratos", "Personas").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PersonasReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Personas)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Contratos", "Personas")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personas)("CSAdminBDModel.Personas_Contratos", "Personas", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for SituacionesProfesionales in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "SituacionesProfesionales_Contratos", "SituacionesProfesionales"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property SituacionesProfesionales() As SituacionesProfesionales
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SituacionesProfesionales)("CSAdminBDModel.SituacionesProfesionales_Contratos", "SituacionesProfesionales").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SituacionesProfesionales)("CSAdminBDModel.SituacionesProfesionales_Contratos", "SituacionesProfesionales").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for SituacionesProfesionales in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property SituacionesProfesionalesReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of SituacionesProfesionales)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SituacionesProfesionales)("CSAdminBDModel.SituacionesProfesionales_Contratos", "SituacionesProfesionales")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SituacionesProfesionales)("CSAdminBDModel.SituacionesProfesionales_Contratos", "SituacionesProfesionales", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for CSAdminBDModel.Equipos in the schema.
'''</summary>
'''<KeyProperties>
'''Id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Equipos"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Equipos
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Equipos object.
    '''</summary>
    '''<param name="id">Initial value of Id.</param>
    '''<param name="ubicacion">Initial value of Ubicacion.</param>
    '''<param name="localidad">Initial value of Localidad.</param>
    Public Shared Function CreateEquipos(ByVal id As String, ByVal ubicacion As String, ByVal localidad As String) As Equipos
        Dim equipos As Equipos = New Equipos
        equipos.Id = id
        equipos.Ubicacion = ubicacion
        equipos.Localidad = localidad
        Return equipos
    End Function
    '''<summary>
    '''There are no comments for Property Id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Id() As String
        Get
            Return Me._Id
        End Get
        Set
            Me.OnIdChanging(value)
            Me.ReportPropertyChanging("Id")
            Me._Id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Id")
            Me.OnIdChanged
        End Set
    End Property
    Private _Id As String
    Partial Private Sub OnIdChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnIdChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Ubicacion in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Ubicacion() As String
        Get
            Return Me._Ubicacion
        End Get
        Set
            Me.OnUbicacionChanging(value)
            Me.ReportPropertyChanging("Ubicacion")
            Me._Ubicacion = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Ubicacion")
            Me.OnUbicacionChanged
        End Set
    End Property
    Private _Ubicacion As String
    Partial Private Sub OnUbicacionChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnUbicacionChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Localidad in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Localidad() As String
        Get
            Return Me._Localidad
        End Get
        Set
            Me.OnLocalidadChanging(value)
            Me.ReportPropertyChanging("Localidad")
            Me._Localidad = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Localidad")
            Me.OnLocalidadChanged
        End Set
    End Property
    Private _Localidad As String
    Partial Private Sub OnLocalidadChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnLocalidadChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Correo in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Correo() As String
        Get
            Return Me._Correo
        End Get
        Set
            Me.OnCorreoChanging(value)
            Me.ReportPropertyChanging("Correo")
            Me._Correo = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Correo")
            Me.OnCorreoChanged
        End Set
    End Property
    Private _Correo As String
    Partial Private Sub OnCorreoChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnCorreoChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Contraseña in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Contraseña() As String
        Get
            Return Me._Contraseña
        End Get
        Set
            Me.OnContraseñaChanging(value)
            Me.ReportPropertyChanging("Contraseña")
            Me._Contraseña = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Contraseña")
            Me.OnContraseñaChanged
        End Set
    End Property
    Private _Contraseña As String
    Partial Private Sub OnContraseñaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnContraseñaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Telefono in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Telefono() As Global.System.Nullable(Of Decimal)
        Get
            Return Me._Telefono
        End Get
        Set
            Me.OnTelefonoChanging(value)
            Me.ReportPropertyChanging("Telefono")
            Me._Telefono = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Telefono")
            Me.OnTelefonoChanged
        End Set
    End Property
    Private _Telefono As Global.System.Nullable(Of Decimal)
    Partial Private Sub OnTelefonoChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
    Partial Private Sub OnTelefonoChanged()
        End Sub
    '''<summary>
    '''There are no comments for Contratos in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Equipos_Contratos", "Contratos"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Contratos() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Contratos)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Contratos)("CSAdminBDModel.Equipos_Contratos", "Contratos")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Contratos)("CSAdminBDModel.Equipos_Contratos", "Contratos", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Equipos", "Personas"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Personas() As Personas
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Equipos", "Personas").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Equipos", "Personas").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PersonasReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Personas)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Equipos", "Personas")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personas)("CSAdminBDModel.Personas_Equipos", "Personas", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for CSAdminBDModel.Funciones in the schema.
'''</summary>
'''<KeyProperties>
'''Id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Funciones"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Funciones
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Funciones object.
    '''</summary>
    '''<param name="id">Initial value of Id.</param>
    '''<param name="funcion">Initial value of Funcion.</param>
    Public Shared Function CreateFunciones(ByVal id As String, ByVal funcion As String) As Funciones
        Dim funciones As Funciones = New Funciones
        funciones.Id = id
        funciones.Funcion = funcion
        Return funciones
    End Function
    '''<summary>
    '''There are no comments for Property Id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Id() As String
        Get
            Return Me._Id
        End Get
        Set
            Me.OnIdChanging(value)
            Me.ReportPropertyChanging("Id")
            Me._Id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Id")
            Me.OnIdChanged
        End Set
    End Property
    Private _Id As String
    Partial Private Sub OnIdChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnIdChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Funcion in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Funcion() As String
        Get
            Return Me._Funcion
        End Get
        Set
            Me.OnFuncionChanging(value)
            Me.ReportPropertyChanging("Funcion")
            Me._Funcion = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Funcion")
            Me.OnFuncionChanged
        End Set
    End Property
    Private _Funcion As String
    Partial Private Sub OnFuncionChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnFuncionChanged()
        End Sub
    '''<summary>
    '''There are no comments for Contratos in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Funciones_Contratos", "Contratos"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Contratos() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Contratos)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Contratos)("CSAdminBDModel.Funciones_Contratos", "Contratos")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Contratos)("CSAdminBDModel.Funciones_Contratos", "Contratos", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for CSAdminBDModel.Inasistencias in the schema.
'''</summary>
'''<KeyProperties>
'''Id
'''IdPersona
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Inasistencias"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Inasistencias
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Inasistencias object.
    '''</summary>
    '''<param name="id">Initial value of Id.</param>
    '''<param name="idPersona">Initial value of IdPersona.</param>
    '''<param name="desde">Initial value of Desde.</param>
    '''<param name="hasta">Initial value of Hasta.</param>
    Public Shared Function CreateInasistencias(ByVal id As Integer, ByVal idPersona As Integer, ByVal desde As Date, ByVal hasta As Date) As Inasistencias
        Dim inasistencias As Inasistencias = New Inasistencias
        inasistencias.Id = id
        inasistencias.IdPersona = idPersona
        inasistencias.Desde = desde
        inasistencias.Hasta = hasta
        Return inasistencias
    End Function
    '''<summary>
    '''There are no comments for Property Id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Id() As Integer
        Get
            Return Me._Id
        End Get
        Set
            Me.OnIdChanging(value)
            Me.ReportPropertyChanging("Id")
            Me._Id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Id")
            Me.OnIdChanged
        End Set
    End Property
    Private _Id As Integer
    Partial Private Sub OnIdChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIdChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property IdPersona in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property IdPersona() As Integer
        Get
            Return Me._IdPersona
        End Get
        Set
            Me.OnIdPersonaChanging(value)
            Me.ReportPropertyChanging("IdPersona")
            Me._IdPersona = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IdPersona")
            Me.OnIdPersonaChanged
        End Set
    End Property
    Private _IdPersona As Integer
    Partial Private Sub OnIdPersonaChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIdPersonaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Desde in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Desde() As Date
        Get
            Return Me._Desde
        End Get
        Set
            Me.OnDesdeChanging(value)
            Me.ReportPropertyChanging("Desde")
            Me._Desde = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Desde")
            Me.OnDesdeChanged
        End Set
    End Property
    Private _Desde As Date
    Partial Private Sub OnDesdeChanging(ByVal value As Date)
        End Sub
    Partial Private Sub OnDesdeChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Hasta in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Hasta() As Date
        Get
            Return Me._Hasta
        End Get
        Set
            Me.OnHastaChanging(value)
            Me.ReportPropertyChanging("Hasta")
            Me._Hasta = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Hasta")
            Me.OnHastaChanged
        End Set
    End Property
    Private _Hasta As Date
    Partial Private Sub OnHastaChanging(ByVal value As Date)
        End Sub
    Partial Private Sub OnHastaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Motivo in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Motivo() As String
        Get
            Return Me._Motivo
        End Get
        Set
            Me.OnMotivoChanging(value)
            Me.ReportPropertyChanging("Motivo")
            Me._Motivo = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Motivo")
            Me.OnMotivoChanged
        End Set
    End Property
    Private _Motivo As String
    Partial Private Sub OnMotivoChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnMotivoChanged()
        End Sub
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Inasistencias", "Personas"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Personas() As Personas
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Inasistencias", "Personas").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Inasistencias", "Personas").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PersonasReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Personas)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_Inasistencias", "Personas")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personas)("CSAdminBDModel.Personas_Inasistencias", "Personas", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for CSAdminBDModel.Personas in the schema.
'''</summary>
'''<KeyProperties>
'''ID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Personas"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Personas
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Personas object.
    '''</summary>
    '''<param name="id">Initial value of ID.</param>
    '''<param name="dNI">Initial value of DNI.</param>
    '''<param name="nombre">Initial value of Nombre.</param>
    '''<param name="apellido">Initial value of Apellido.</param>
    '''<param name="baja">Initial value of Baja.</param>
    Public Shared Function CreatePersonas(ByVal id As Integer, ByVal dNI As Decimal, ByVal nombre As String, ByVal apellido As String, ByVal baja As Boolean) As Personas
        Dim personas As Personas = New Personas
        personas.ID = id
        personas.DNI = dNI
        personas.Nombre = nombre
        personas.Apellido = apellido
        personas.Baja = baja
        Return personas
    End Function
    '''<summary>
    '''There are no comments for Property ID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property ID() As Integer
        Get
            Return Me._ID
        End Get
        Set
            Me.OnIDChanging(value)
            Me.ReportPropertyChanging("ID")
            Me._ID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ID")
            Me.OnIDChanged
        End Set
    End Property
    Private _ID As Integer
    Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property DNI in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property DNI() As Decimal
        Get
            Return Me._DNI
        End Get
        Set
            Me.OnDNIChanging(value)
            Me.ReportPropertyChanging("DNI")
            Me._DNI = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("DNI")
            Me.OnDNIChanged
        End Set
    End Property
    Private _DNI As Decimal
    Partial Private Sub OnDNIChanging(ByVal value As Decimal)
        End Sub
    Partial Private Sub OnDNIChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property CUIT in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property CUIT() As Global.System.Nullable(Of Decimal)
        Get
            Return Me._CUIT
        End Get
        Set
            Me.OnCUITChanging(value)
            Me.ReportPropertyChanging("CUIT")
            Me._CUIT = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("CUIT")
            Me.OnCUITChanged
        End Set
    End Property
    Private _CUIT As Global.System.Nullable(Of Decimal)
    Partial Private Sub OnCUITChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
    Partial Private Sub OnCUITChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Nombre in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Nombre() As String
        Get
            Return Me._Nombre
        End Get
        Set
            Me.OnNombreChanging(value)
            Me.ReportPropertyChanging("Nombre")
            Me._Nombre = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Nombre")
            Me.OnNombreChanged
        End Set
    End Property
    Private _Nombre As String
    Partial Private Sub OnNombreChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNombreChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Apellido in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Apellido() As String
        Get
            Return Me._Apellido
        End Get
        Set
            Me.OnApellidoChanging(value)
            Me.ReportPropertyChanging("Apellido")
            Me._Apellido = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Apellido")
            Me.OnApellidoChanged
        End Set
    End Property
    Private _Apellido As String
    Partial Private Sub OnApellidoChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnApellidoChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Direccion in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Direccion() As String
        Get
            Return Me._Direccion
        End Get
        Set
            Me.OnDireccionChanging(value)
            Me.ReportPropertyChanging("Direccion")
            Me._Direccion = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Direccion")
            Me.OnDireccionChanged
        End Set
    End Property
    Private _Direccion As String
    Partial Private Sub OnDireccionChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnDireccionChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Correo in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Correo() As String
        Get
            Return Me._Correo
        End Get
        Set
            Me.OnCorreoChanging(value)
            Me.ReportPropertyChanging("Correo")
            Me._Correo = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Correo")
            Me.OnCorreoChanged
        End Set
    End Property
    Private _Correo As String
    Partial Private Sub OnCorreoChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnCorreoChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Baja in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Baja() As Boolean
        Get
            Return Me._Baja
        End Get
        Set
            Me.OnBajaChanging(value)
            Me.ReportPropertyChanging("Baja")
            Me._Baja = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Baja")
            Me.OnBajaChanged
        End Set
    End Property
    Private _Baja As Boolean
    Partial Private Sub OnBajaChanging(ByVal value As Boolean)
        End Sub
    Partial Private Sub OnBajaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Contratos in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Contratos", "Contratos"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Contratos() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Contratos)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Contratos)("CSAdminBDModel.Personas_Contratos", "Contratos")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Contratos)("CSAdminBDModel.Personas_Contratos", "Contratos", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Equipos in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Equipos", "Equipos"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Equipos() As Equipos
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Equipos)("CSAdminBDModel.Personas_Equipos", "Equipos").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Equipos)("CSAdminBDModel.Personas_Equipos", "Equipos").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Equipos in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property EquiposReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Equipos)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Equipos)("CSAdminBDModel.Personas_Equipos", "Equipos")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Equipos)("CSAdminBDModel.Personas_Equipos", "Equipos", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Inasistencias in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_Inasistencias", "Inasistencias"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Inasistencias() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Inasistencias)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Inasistencias)("CSAdminBDModel.Personas_Inasistencias", "Inasistencias")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Inasistencias)("CSAdminBDModel.Personas_Inasistencias", "Inasistencias", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for PersonasTel in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_PersonasTel", "PersonasTel"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PersonasTel() As Global.System.Data.Objects.DataClasses.EntityCollection(Of PersonasTel)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of PersonasTel)("CSAdminBDModel.Personas_PersonasTel", "PersonasTel")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of PersonasTel)("CSAdminBDModel.Personas_PersonasTel", "PersonasTel", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Usuarios in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Usuarios_Personas", "Usuarios"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Usuarios() As Usuarios
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Usuarios)("CSAdminBDModel.Usuarios_Personas", "Usuarios").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Usuarios)("CSAdminBDModel.Usuarios_Personas", "Usuarios").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Usuarios in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property UsuariosReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Usuarios)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Usuarios)("CSAdminBDModel.Usuarios_Personas", "Usuarios")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Usuarios)("CSAdminBDModel.Usuarios_Personas", "Usuarios", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for CSAdminBDModel.PersonasTel in the schema.
'''</summary>
'''<KeyProperties>
'''IdPersona
'''Tipo
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="PersonasTel"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class PersonasTel
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new PersonasTel object.
    '''</summary>
    '''<param name="idPersona">Initial value of IdPersona.</param>
    '''<param name="tipo">Initial value of Tipo.</param>
    '''<param name="numero">Initial value of Numero.</param>
    Public Shared Function CreatePersonasTel(ByVal idPersona As Integer, ByVal tipo As String, ByVal numero As Decimal) As PersonasTel
        Dim personasTel As PersonasTel = New PersonasTel
        personasTel.IdPersona = idPersona
        personasTel.Tipo = tipo
        personasTel.Numero = numero
        Return personasTel
    End Function
    '''<summary>
    '''There are no comments for Property IdPersona in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property IdPersona() As Integer
        Get
            Return Me._IdPersona
        End Get
        Set
            Me.OnIdPersonaChanging(value)
            Me.ReportPropertyChanging("IdPersona")
            Me._IdPersona = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IdPersona")
            Me.OnIdPersonaChanged
        End Set
    End Property
    Private _IdPersona As Integer
    Partial Private Sub OnIdPersonaChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIdPersonaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Tipo in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Tipo() As String
        Get
            Return Me._Tipo
        End Get
        Set
            Me.OnTipoChanging(value)
            Me.ReportPropertyChanging("Tipo")
            Me._Tipo = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Tipo")
            Me.OnTipoChanged
        End Set
    End Property
    Private _Tipo As String
    Partial Private Sub OnTipoChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnTipoChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Numero in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Numero() As Decimal
        Get
            Return Me._Numero
        End Get
        Set
            Me.OnNumeroChanging(value)
            Me.ReportPropertyChanging("Numero")
            Me._Numero = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Numero")
            Me.OnNumeroChanged
        End Set
    End Property
    Private _Numero As Decimal
    Partial Private Sub OnNumeroChanging(ByVal value As Decimal)
        End Sub
    Partial Private Sub OnNumeroChanged()
        End Sub
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Personas_PersonasTel", "Personas"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Personas() As Personas
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_PersonasTel", "Personas").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_PersonasTel", "Personas").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PersonasReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Personas)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Personas_PersonasTel", "Personas")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personas)("CSAdminBDModel.Personas_PersonasTel", "Personas", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for CSAdminBDModel.SituacionesProfesionales in the schema.
'''</summary>
'''<KeyProperties>
'''CargoAbrev
'''CondicionAbrev
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="SituacionesProfesionales"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class SituacionesProfesionales
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new SituacionesProfesionales object.
    '''</summary>
    '''<param name="cargoAbrev">Initial value of CargoAbrev.</param>
    '''<param name="cargo">Initial value of Cargo.</param>
    '''<param name="condicionAbrev">Initial value of CondicionAbrev.</param>
    '''<param name="condicion">Initial value of Condicion.</param>
    Public Shared Function CreateSituacionesProfesionales(ByVal cargoAbrev As String, ByVal cargo As String, ByVal condicionAbrev As String, ByVal condicion As String) As SituacionesProfesionales
        Dim situacionesProfesionales As SituacionesProfesionales = New SituacionesProfesionales
        situacionesProfesionales.CargoAbrev = cargoAbrev
        situacionesProfesionales.Cargo = cargo
        situacionesProfesionales.CondicionAbrev = condicionAbrev
        situacionesProfesionales.Condicion = condicion
        Return situacionesProfesionales
    End Function
    '''<summary>
    '''There are no comments for Property CargoAbrev in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property CargoAbrev() As String
        Get
            Return Me._CargoAbrev
        End Get
        Set
            Me.OnCargoAbrevChanging(value)
            Me.ReportPropertyChanging("CargoAbrev")
            Me._CargoAbrev = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("CargoAbrev")
            Me.OnCargoAbrevChanged
        End Set
    End Property
    Private _CargoAbrev As String
    Partial Private Sub OnCargoAbrevChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnCargoAbrevChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Cargo in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Cargo() As String
        Get
            Return Me._Cargo
        End Get
        Set
            Me.OnCargoChanging(value)
            Me.ReportPropertyChanging("Cargo")
            Me._Cargo = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Cargo")
            Me.OnCargoChanged
        End Set
    End Property
    Private _Cargo As String
    Partial Private Sub OnCargoChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnCargoChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property CondicionAbrev in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property CondicionAbrev() As String
        Get
            Return Me._CondicionAbrev
        End Get
        Set
            Me.OnCondicionAbrevChanging(value)
            Me.ReportPropertyChanging("CondicionAbrev")
            Me._CondicionAbrev = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("CondicionAbrev")
            Me.OnCondicionAbrevChanged
        End Set
    End Property
    Private _CondicionAbrev As String
    Partial Private Sub OnCondicionAbrevChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnCondicionAbrevChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Condicion in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Condicion() As String
        Get
            Return Me._Condicion
        End Get
        Set
            Me.OnCondicionChanging(value)
            Me.ReportPropertyChanging("Condicion")
            Me._Condicion = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Condicion")
            Me.OnCondicionChanged
        End Set
    End Property
    Private _Condicion As String
    Partial Private Sub OnCondicionChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnCondicionChanged()
        End Sub
    '''<summary>
    '''There are no comments for Contratos in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "SituacionesProfesionales_Contratos", "Contratos"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Contratos() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Contratos)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Contratos)("CSAdminBDModel.SituacionesProfesionales_Contratos", "Contratos")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Contratos)("CSAdminBDModel.SituacionesProfesionales_Contratos", "Contratos", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for CSAdminBDModel.Usuarios in the schema.
'''</summary>
'''<KeyProperties>
'''Usuario
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="CSAdminBDModel", Name:="Usuarios"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Usuarios
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Usuarios object.
    '''</summary>
    '''<param name="usuario">Initial value of Usuario.</param>
    '''<param name="contraseña">Initial value of Contraseña.</param>
    '''<param name="rol">Initial value of Rol.</param>
    Public Shared Function CreateUsuarios(ByVal usuario As String, ByVal contraseña As String, ByVal rol As String) As Usuarios
        Dim usuarios As Usuarios = New Usuarios
        usuarios.Usuario = usuario
        usuarios.Contraseña = contraseña
        usuarios.Rol = rol
        Return usuarios
    End Function
    '''<summary>
    '''There are no comments for Property Usuario in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Usuario() As String
        Get
            Return Me._Usuario
        End Get
        Set
            Me.OnUsuarioChanging(value)
            Me.ReportPropertyChanging("Usuario")
            Me._Usuario = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Usuario")
            Me.OnUsuarioChanged
        End Set
    End Property
    Private _Usuario As String
    Partial Private Sub OnUsuarioChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnUsuarioChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Contraseña in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Contraseña() As String
        Get
            Return Me._Contraseña
        End Get
        Set
            Me.OnContraseñaChanging(value)
            Me.ReportPropertyChanging("Contraseña")
            Me._Contraseña = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Contraseña")
            Me.OnContraseñaChanged
        End Set
    End Property
    Private _Contraseña As String
    Partial Private Sub OnContraseñaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnContraseñaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Rol in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Rol() As String
        Get
            Return Me._Rol
        End Get
        Set
            Me.OnRolChanging(value)
            Me.ReportPropertyChanging("Rol")
            Me._Rol = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Rol")
            Me.OnRolChanged
        End Set
    End Property
    Private _Rol As String
    Partial Private Sub OnRolChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnRolChanged()
        End Sub
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSAdminBDModel", "Usuarios_Personas", "Personas"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Personas() As Personas
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Usuarios_Personas", "Personas").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Usuarios_Personas", "Personas").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Personas in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PersonasReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Personas)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Personas)("CSAdminBDModel.Usuarios_Personas", "Personas")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Personas)("CSAdminBDModel.Usuarios_Personas", "Personas", value)
            End If
        End Set
    End Property
End Class
