//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAdminApp.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public Equipos()
        {
            this.Contratos = new HashSet<Contratos>();
        }
    
        public string Id { get; set; }
        public string Ubicacion { get; set; }
        public int LocalidadId { get; set; }
        public string Correo { get; set; }
        public string Contra { get; set; }
        public Nullable<decimal> Telefono { get; set; }
        public int CoordinadoId { get; set; }
    
        public virtual ICollection<Contratos> Contratos { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
