//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAdminApp.Clases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSAdminBDEntities : DbContext
    {
        public CSAdminBDEntities()
            : base("name=CSAdminBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contratos> Contratos { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Funciones> Funciones { get; set; }
        public virtual DbSet<Inasistencias> Inasistencias { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<PersonasTel> PersonasTel { get; set; }
        public virtual DbSet<SituacionesProfesionales> SituacionesProfesionales { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
