//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAdminApp.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public Personas()
        {
            this.Contratos = new HashSet<Contratos>();
            this.Equipos = new HashSet<Equipos>();
            this.Inasistencias = new HashSet<Inasistencias>();
            this.PersonasTel = new HashSet<PersonasTel>();
        }
    
        public int Id { get; set; }
        public decimal Dni { get; set; }
        public Nullable<decimal> Cuit { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public bool Baja { get; set; }
    
        public virtual ICollection<Contratos> Contratos { get; set; }
        public virtual ICollection<Equipos> Equipos { get; set; }
        public virtual ICollection<Inasistencias> Inasistencias { get; set; }
        public virtual ICollection<PersonasTel> PersonasTel { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
