//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAdminApp.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonasTel
    {
        public int IdPersona { get; set; }
        public string Tipo { get; set; }
        public decimal Numero { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
